# Write src/zig_tables.jl, the Float64 normal ziggurat tables, from the spec's table file:
#
#     julia tools/gen_zig_tables.jl ../tandem-spec/tables/normal_f64_zig1024.json > src/zig_tables.jl
#
# The file's SHA-256 must match the value the spec publishes, so a changed table file fails
# here instead of changing the normals. Each Float64 keeps its exact hexadecimal form, which
# Julia parses as a literal.

using Printf, SHA

const SPEC_SHA256 = "8b961dd46a2582b953bd8780138edb0ad712e3d243a366a123ffc8978d0a33ab"
const LAYERS = 1024

function hexfloats(text, name)
    body = match(Regex("\"$name\"\\s*:\\s*\\[([^\\]]*)\\]"), text)[1]
    values = [m[1] for m in eachmatch(r"\"([^\"]+)\"", body)]
    for s in values
        x = parse(Float64, s)
        # Canonical form: the literal round-trips to itself.
        @sprintf("%.13a", x) == s || error("not a canonical hexadecimal float: $s")
    end
    return values
end

function rows(values, per_line)
    lines = ["    " * join(values[i:min(end, i + per_line - 1)], ", ") * ","
             for i = 1:per_line:length(values)]
    return join(lines, "\n")
end

function main(path)
    data = read(path)
    digest = bytes2hex(sha256(data))
    digest == SPEC_SHA256 || error("$path: SHA-256 $digest, expected $SPEC_SHA256")
    text = String(data)
    parse(Int, match(r"\"layers\"\s*:\s*(\d+)", text)[1]) == LAYERS || error("unexpected layers")
    r = match(r"\"R\"\s*:\s*\"([^\"]+)\"", text)[1]
    w = hexfloats(text, "W")
    y = hexfloats(text, "Y")
    k = [m.match for m in eachmatch(r"\d+", match(r"\"K\"\s*:\s*\[([^\]]*)\]", text)[1])]
    length(w) == LAYERS && length(k) == LAYERS && length(y) == LAYERS + 1 ||
        error("unexpected table sizes")
    print("""
    # Generated by tools/gen_zig_tables.jl from the spec's tables/normal_f64_zig1024.json
    # (SHA-256 $SPEC_SHA256). Do not edit.
    #
    # The Float64 normal ziggurat of Appendix A with $LAYERS layers. ZIG_W holds the widths W[i]
    # for a clear sign bit and -W[i] at $LAYERS + i for a set one, so the index is the low 11 bits
    # of a draw.

    const ZIG_R = $r

    const ZIG_W = Float64[
    $(rows(vcat(w, "-" .* w), 4))
    ]

    const ZIG_K = UInt64[
    $(rows(k, 4))
    ]

    const ZIG_Y = Float64[
    $(rows(y, 4))
    ]
    """)
end

main(ARGS[1])
